options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "instances"
      - "reset"
      - "instance-20240425-125736"
      - "--zone=asia-east1-b"
