options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "instance-20240425-125736"
      - "--zone=asia-east1-b"
      - "--ssh-key-file=/home/see8982689826/.ssh/id_rsa"
      - "--command=cd shopingo-backend/ && \
        git pull && \
        source Django_framework/myenv/bin/activate && \
        pip install --no-cache-dir -r Django_framework/requirements.txt && \
        pkill gunicorn && \
        cd Django_framework/ && \
        gunicorn Django_framework.wsgi:application --bind 0.0.0.0:8000 --daemon"
