# Generated by Django 4.2.11 on 2024-04-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('hashtag', models.JSONField()),
                ('location', models.CharField(max_length=32)),
                ('event_date', models.DateTimeField()),
                ('scale', models.CharField(max_length=32)),
                ('budget', models.IntegerField()),
                ('detail', models.TextField()),
                ('create_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('delete_datetime', models.DateTimeField(null=True)),
                ('score', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
