# Generated by Django 4.2.11 on 2024-05-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('event', 'url')},
        ),
    ]
