# Generated by Django 4.2.11 on 2024-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_image_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="coordinate",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="score",
            field=models.IntegerField(null=True),
        ),
    ]
