# Generated by Django 4.2.11 on 2024-05-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_calendarid'),
        ('event', '0005_event_coordinate_event_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='calendarEventId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
