# Generated by Django 4.2.11 on 2024-05-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_participant_calendareventid_savedevent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usereventscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usereventscore',
            name='target',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usereventscore',
            unique_together={('user', 'event', 'target')},
        ),
    ]
