# Generated by Django 4.2.11 on 2024-05-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_participant_calendareventid_savedevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='event_id',
        ),
    ]
