# Generated by Django 4.2.11 on 2024-05-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_id_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
    ]
