# Generated by Django 4.2.11 on 2024-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_event_id_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
