# Generated by Django 4.2.11 on 2024-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('gmail', models.EmailField(max_length=256)),
                ('profile_pic', models.URLField(max_length=256)),
                ('score', models.IntegerField(default=100)),
            ],
        ),
    ]
