# Generated by Django 4.2.11 on 2024-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id_alter_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score_amounts',
            field=models.IntegerField(default=0),
        ),
    ]
