# Generated by Django 4.2.11 on 2024-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_score_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
    ]
